image: Previous Visual Studio 2019

build: off

clone_folder: c:\gopath\src\github.com\go-python\gopy

cache:
  - '%LocalAppData%\\go-build'
  - '%LocalAppData%\\pip'

branches:
  only:
    - master

environment:
  GOROOT: C:\go122
  GOPY_APPVEYOR_CI: '1'
  GOTRACEBACK: 'crash'
  CPYTHON3DIR: "C:\\Python311-x64"
  PATH: 'C:\go122\bin;%USERPROFILE%\go\bin;%CPYTHON3DIR%;%CPYTHON3DIR%\\Scripts;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%'

build_script:
  - python --version
  - "python -m pip install --upgrade pip"
  - "python -m pip install cffi"
  - "python -m pip install pybindgen"
  - "where go"
  - "C:\\go122\\bin\\go.exe version"
  - go version
  - go env
  - go get -v -t ./...
  - go install golang.org/x/tools/cmd/goimports

test_script:
  - go test ./...
