// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.4"
	GitCommit   = "2a31e2f"          // the commit JUST BEFORE the release
	VersionDate = "2022-07-01 06:31" // UTC
)
