// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version = "v0.3.5"
	GitCommit = "86b4a9b" // the commit JUST BEFORE the release
	VersionDate = "2021-08-28 11:27" // UTC
)

