// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.2"
	GitCommit   = "406f982"          // the commit JUST BEFORE the release
	VersionDate = "2022-06-19 09:05" // UTC
)
