// Package py_hi is an autogenerated binder stub for package hi.
// gopy-gen -lang=go hi
//
// File is generated by gopy-gen. Do not edit.
package py_hi

// void inithi(void);
import "C"

import (
	"github.com/go-python/gopy-gen/_examples/hi"
)


//export GoPy_Add
// GoPy_Add wraps github.com/go-python/gopy-gen/_examples/hi.Add
func GoPy_Add(i int, j int) int {
	return hi.Add(i, j)
}


//export GoPy_Concat
// GoPy_Concat wraps github.com/go-python/gopy-gen/_examples/hi.Concat
func GoPy_Concat(s1 string, s2 string) string {
	return hi.Concat(s1, s2)
}


//export GoPy_Hello
// GoPy_Hello wraps github.com/go-python/gopy-gen/_examples/hi.Hello
func GoPy_Hello(s string) {
	hi.Hello(s)
}


//export GoPy_Hi
// GoPy_Hi wraps github.com/go-python/gopy-gen/_examples/hi.Hi
func GoPy_Hi() {
	hi.Hi()
}

// Register registers the generated CPython module with the CPython runtime
func Register() {
	C.inithi()
}
