# Copyright 2020 go-python Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# py2/py3 compat
from __future__ import print_function

import gopyerrors

# This is empty, its only purpose is to have a test that catches
# errors generated by the gopy itself.

print("OK")
