# python build stubs for package @NAME@ (capi backend)
# File is generated by gopy version @VERSION@. Do not edit.
# @CMD@
#
# The generated build code below is written against the pybindgen API.  Here
# the same calls are only recorded, and Module.generate() then writes
# @NAME@.c itself: the same CPython C-API wrappers pybindgen would write, for
# the same cgo shim, so nothing beyond the interpreter is needed to build.
# Every conversion below follows pybindgen's own generated code, so that a
# wrongly-typed argument raises the same exception under either backend.


class Retval(object):
    def __init__(self, ctype, caller_owns_return=False, *a, **kw):
        self.ctype = ctype


class Param(object):
    def __init__(self, ctype, name, transfer_ownership=True, *a, **kw):
        self.ctype = ctype
        self.name = name


retval = Retval
param = Param


class Function(object):
    def __init__(self, name, ret, params, checked=False, frees_string=False):
        self.name = name
        self.ret = ret.ctype if ret is not None else None
        self.params = params
        self.checked = checked
        self.frees_string = frees_string


class Module(object):
    def __init__(self, name, *a, **kw):
        self.name = name  # the compiled extension's import name, e.g. "_hi"
        self.includes = []
        self.funcs = []

    def add_include(self, inc):
        self.includes.append(inc)

    def add_function(self, name, ret, params, *a, **kw):
        self.funcs.append(Function(name, ret, params))

    def generate(self, out):
        out.write(MODULE_HEAD.replace("@INCLUDES@", "\n".join("#include " + i for i in self.includes)))
        for fn in self.funcs:
            out.write(wrapper(self.name, fn))
        out.write("static PyMethodDef %s_functions[] = {\n" % self.name)
        for fn in self.funcs:
            flags = "METH_VARARGS|METH_KEYWORDS" if fn.params else "METH_NOARGS"
            out.write('    {"%s", (PyCFunction)%s, %s, "%s"},\n' % (fn.name, wrap_name(self.name, fn), flags, doc(fn)))
        out.write("    {NULL, NULL, 0, NULL}\n};\n")
        out.write(MODULE_TAIL.replace("@MOD@", self.name))
        out.close()


# failure_expression is never anything but '' from gopy, so a checked
# function's only check is PyErr_Occurred(), as with pybindgen.
def add_checked_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.funcs.append(Function(name, retval, params, checked=True))


# As above, and the char* the function returns is the caller's to free.
def add_checked_string_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.funcs.append(Function(name, retval, params, checked=True, frees_string=True))


# ctype -> (PyArg_Parse format, C type parsed into, maximum value or None).
# Narrow integers parse as int, and only their maximum is checked.
PARSE = {
    "int64_t": ("L", "int64_t", None),
    "uint64_t": ("K", "uint64_t", None),
    "int": ("i", "int", None),
    "int32_t": ("i", "int", None),
    "uint32_t": ("I", "unsigned int", None),
    "int16_t": ("i", "int", "0x7fff"),
    "uint16_t": ("i", "int", "0xffff"),
    "int8_t": ("i", "int", "0x7f"),
    "uint8_t": ("i", "int", "0xff"),
    "double": ("d", "double", None),
    "float": ("f", "float", None),
    "bool": ("O", "PyObject *", None),
    "char*": ("s", "const char *", None),
    "PyObject*": ("O", "PyObject *", None),
}

# ctype -> Py_BuildValue arguments for the result in "retval".  Py_BuildValue
# turns a NULL char* into None, and passes on a NULL PyObject* as an error.
BUILD = {
    "int64_t": '"L", retval',
    "uint64_t": '"K", retval',
    "int": '"i", retval',
    "int32_t": '"i", retval',
    "int16_t": '"i", retval',
    "uint16_t": '"i", retval',
    "int8_t": '"i", retval',
    "uint8_t": '"i", (int)retval',
    "uint32_t": '"N", PyLong_FromUnsignedLong(retval)',
    "double": '"d", retval',
    "float": '"f", retval',
    "bool": '"N", PyBool_FromLong(retval)',
    "char*": '"s", retval',
    "PyObject*": '"N", retval',
}


def wrap_name(mod, fn):
    return "_wrap_%s_%s" % (mod, fn.name)


def doc(fn):
    sig = "%s(%s)\\n\\n" % (fn.name, ", ".join(p.name for p in fn.params))
    return sig + "\\n".join("type: %s: %s" % (p.name, p.ctype.replace("*", " *")) for p in fn.params)


def wrapper(mod, fn):
    for ctype in [p.ctype for p in fn.params] + ([fn.ret] if fn.ret else []):
        if ctype not in PARSE:
            raise ValueError("capi backend: unsupported C type %r in %s" % (ctype, fn.name))
    if not fn.params:
        lines = ["static PyObject *\n%s(PyObject *self, PyObject *unused)\n{" % wrap_name(mod, fn)]
    else:
        lines = ["static PyObject *\n%s(PyObject *self, PyObject *args, PyObject *kwargs)\n{" % wrap_name(mod, fn)]
    if fn.ret:
        lines.append("    %s retval;" % fn.ret)
    # locals are prefixed, so that no parameter name can collide with them
    call_args = []
    for p in fn.params:
        lines.append("    %s a_%s;" % (PARSE[p.ctype][1], p.name))
        if p.ctype == "bool":
            call_args.append("(bool)PyObject_IsTrue(a_%s)" % p.name)
        elif p.ctype == "char*":
            call_args.append("(char *)a_" + p.name)
        else:
            call_args.append("a_" + p.name)
    if fn.params:
        lines.append(
            "    static const char *keywords[] = {%s, NULL};" % ", ".join('"%s"' % p.name for p in fn.params)
        )
        lines.append(
            '    if (!PyArg_ParseTupleAndKeywords(args, kwargs, "%s", (char **)keywords, %s)) {\n'
            "        return NULL;\n    }"
            % ("".join(PARSE[p.ctype][0] for p in fn.params), ", ".join("&a_" + p.name for p in fn.params))
        )
    for p in fn.params:
        limit = PARSE[p.ctype][2]
        if limit:
            lines.append(
                "    if (a_%s > %s) {\n"
                '        PyErr_SetString(PyExc_ValueError, "Out of range");\n'
                "        return NULL;\n    }" % (p.name, limit)
            )
    call = "%s(%s);" % (fn.name, ", ".join(call_args))
    lines.append("    " + ("retval = " + call if fn.ret else call))
    if fn.checked:
        cleanup = "        if (retval != NULL) free(retval);\n" if fn.frees_string else ""
        lines.append("    if (PyErr_Occurred()) {\n%s        return NULL;\n    }" % cleanup)
    if not fn.ret:
        lines.append("    Py_RETURN_NONE;")
    elif fn.frees_string:
        lines.append("    PyObject *py_retval = Py_BuildValue(%s);" % BUILD[fn.ret])
        lines.append("    free(retval);")
        lines.append("    return py_retval;")
    else:
        lines.append("    return Py_BuildValue(%s);" % BUILD[fn.ret])
    lines.append("}\n\n")
    return "\n".join(lines)


MODULE_HEAD = """/* This file was generated by gopy's capi backend. Do not edit. */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdlib.h>

@INCLUDES@

"""

# PyInit_ starts its own line: on Windows, cmd_build.go adds
# __declspec(dllexport) after any " PyInit_" in the file, which
# PyMODINIT_FUNC already has.
MODULE_TAIL = """
static struct PyModuleDef @MOD@_moduledef = {
    PyModuleDef_HEAD_INIT,
    "@MOD@",
    NULL,
    -1,
    @MOD@_functions,
};

PyMODINIT_FUNC
PyInit_@MOD@(void)
{
    return PyModule_Create(&@MOD@_moduledef);
}
"""


mod = Module('_@NAME@')
mod.add_include('"@NAME@_go.h"')
mod.add_function('GoPyInit', None, [])
mod.add_function('DecRef', None, [param('int64_t', 'handle')])
mod.add_function('IncRef', None, [param('int64_t', 'handle')])
mod.add_function('NumHandles', retval('int'), [])
mod.add_function('RequestGC', None, [])
mod.add_function('_gopy_clear_go_tls', None, [])
