// Copyright 2026 The go-python Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bind

import (
	_ "embed"
	"strings"
)

// The cffi backend (GOPY_BACKEND=cffi) uses the shared no-API cgo shim (see
// noapi.go): a plain C shared library that Python loads with cffi.  Errors
// are recorded for the Python side to raise, instead of being set with
// PyErr_SetString.

//go:embed cffi_build.py
var cffiBuildPy string

// cffiBuildPreamble returns the start of build.py: the cffi recorder.
func (g *pyGen) cffiBuildPreamble() string {
	return strings.NewReplacer(
		"@NAME@", g.cfg.Name,
		"@CMD@", g.cfg.Cmd,
		"@VERSION@", g.cfg.Version,
		"@LIBEXT@", g.libext,
	).Replace(cffiBuildPy)
}

// same argument positions as goPreamble: 1 = name of package, 2 = cmdstr,
// 4 = GoHandle, 5 = CGoHandle, 6 = all imports, 7 = mainstr, 8 = C trampolines for
// callbacks (see cffi_callback.go), 10 = gopy version.
const goPreambleCFFI = `/*
cgo stubs for package %[1]s, for use with cffi or pybind11.
File is generated by gopy version %[10]s. Do not edit.
%[2]s
*/

package main

/*
#include <stdint.h>
#include <stdlib.h>
// pybind11's consumer #includes this same preamble (via the generated
// header) as C++, where bool/thread_local are keywords, not the C ones below.
#if !defined(__cplusplus) && (!defined(__STDC_VERSION__) || (__STDC_VERSION__ < 202311L))
typedef uint8_t bool;
#endif
#if defined(__cplusplus)
#define GOPY_THREAD_LOCAL thread_local
#else
#define GOPY_THREAD_LOCAL _Thread_local
#endif
// Thread-local storage for the last error, read by the python side right
// after the call that set it, on the same OS thread.  Windows gets its own
// branch: mingw's compiler-provided thread-local storage (_Thread_local)
// needs TLS support that a DLL loaded after process start (as cffi and
// ctypes do) isn't guaranteed to have, so this uses the OS API instead,
// which carries no such restriction (see TlsAlloc/TlsGetValue/TlsSetValue).
#ifdef _WIN32
#include <windows.h>
static DWORD gopy_err_tls = TLS_OUT_OF_INDEXES;
static inline void gopy_err_tls_init(void) { gopy_err_tls = TlsAlloc(); }
static inline char* gopy_err_get(void) { return (char*)TlsGetValue(gopy_err_tls); }
static inline void gopy_err_put(char* msg) { TlsSetValue(gopy_err_tls, msg); }
#else
static inline void gopy_err_tls_init(void) {}
static GOPY_THREAD_LOCAL char* gopy_err_msg;
static inline char* gopy_err_get(void) { return gopy_err_msg; }
static inline void gopy_err_put(char* msg) { gopy_err_msg = msg; }
#endif
static inline void gopy_set_err(char* msg) {
	free(gopy_err_get());
	gopy_err_put(msg);
}
static inline char* gopy_take_err(void) {
	char* msg = gopy_err_get();
	gopy_err_put(NULL);
	return msg;
}
%[8]s
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
	"github.com/go-python/gopy/gopyh" // handler
	%[6]s
)

func main() {
	%[7]s
}

//export GoPyInit
func GoPyInit() {
	%[7]s
}

// type for the handle -- int64 for speed (can switch to string)
type GoHandle %[4]s
type CGoHandle %[5]s

// DecRef decrements the reference count for the specified handle
// and deletes it it goes to zero.
//export DecRef
func DecRef(handle CGoHandle) {
	gopyh.DecRef(gopyh.CGoHandle(handle))
}

// IncRef increments the reference count for the specified handle.
//export IncRef
func IncRef(handle CGoHandle) {
	gopyh.IncRef(gopyh.CGoHandle(handle))
}

// NumHandles returns the number of handles currently in use.
//export NumHandles
func NumHandles() int {
	return gopyh.NumHandles()
}

// RequestGC runs Go's garbage collector on a dedicated goroutine, and waits.
//export RequestGC
func RequestGC() {
	done := make(chan struct{})
	_gcReq <- done
	<-done
}

var _gcReq = make(chan chan struct{})

func init() {
	C.gopy_err_tls_init()
	go func() {
		for done := range _gcReq {
			runtime.GC()
			close(done)
		}
	}()
}

// The error of the last call on the calling OS thread, for the python side
// to raise; gopy_err_msg is thread-local so concurrent calls on other
// threads don't see it.
func gopySetError(kind, msg string) {
	C.gopy_set_err(C.CString(kind + ":" + msg))
}

// GopyTakeError returns "Kind:message" for the error recorded by the last
// call on the calling thread and clears it, or NULL if there is none.
// Free with GopyFreeString.
//export GopyTakeError
func GopyTakeError() *C.char {
	return C.gopy_take_err()
}

// GopyFreeString frees a string returned by this library.
//export GopyFreeString
func GopyFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

// gopyCallbackScope guards a python callback passed to Go, which only exists
// while the python call it was passed to is running (see cffi_callback.go):
// close waits for callbacks that are running, and then refuses new ones.
type gopyCallbackScope struct {
	mu   sync.RWMutex
	done bool
}

func (s *gopyCallbackScope) enter() bool {
	s.mu.RLock()
	if s.done {
		s.mu.RUnlock()
		println("gopy: callback called after the python call it was passed to returned")
		return false
	}
	return true
}

func (s *gopyCallbackScope) leave() { s.mu.RUnlock() }

func (s *gopyCallbackScope) close() {
	s.mu.Lock()
	s.done = true
	s.mu.Unlock()
}

// boolGoToPy converts a Go bool to python-compatible C.char
func boolGoToPy(b bool) C.char {
	if b {
		return 1
	}
	return 0
}

// boolPyToGo converts a python-compatible C.Char to Go bool
func boolPyToGo(b C.char) bool {
	return b != 0
}

// errorGoToPy converts a Go error to python-compatible C.CString
func errorGoToPy(e error) *C.char {
	if e != nil {
		return C.CString(e.Error())
	}
	return C.CString("")
}

// complex values cross as two floats, see isComplexShim in cffi.go
func complex64GoToPyCFFI(c complex64) (C.float, C.float) {
	return C.float(real(c)), C.float(imag(c))
}

func complex64PyToGoCFFI(re, im C.float) complex64 {
	return complex(float32(re), float32(im))
}

func complex128GoToPyCFFI(c complex128) (C.double, C.double) {
	return C.double(real(c)), C.double(imag(c))
}

func complex128PyToGoCFFI(re, im C.double) complex128 {
	return complex(float64(re), float64(im))
}
`
