# python build stubs for package @NAME@ (cffi backend)
# File is generated by gopy version @VERSION@. Do not edit.
# @CMD@
#
# The generated build code below is written against the pybindgen API.  Here
# the same calls are only recorded, and Module.generate() then writes a cffi
# (ABI mode) module, _@NAME@.py, that loads @NAME@_go@LIBEXT@ directly.  The
# exact C types come from the extern declarations in cgo's @NAME@_go.h.

import os
import re
import sys

import cffi


def retval(ctype, *a, **kw):
    return ctype


def param(ctype, name, *a, **kw):
    return (ctype, name)


class Module(object):
    def __init__(self, name):
        self.name = name
        self.header = None
        self.funcs = []

    def add_include(self, inc):
        self.header = inc.strip('"')

    def add_function(self, name, ret, params, *a, **kw):
        self.funcs.append(("plain", name, ret, params))

    def add_complex_function(self, name, nargs):
        # see genFuncComplexCFFI (gen_func.go) for the calling convention.
        self.funcs.append(("complex", name, nargs))

    def generate(self):
        here = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(here, self.header)) as f:
            typedefs, cdefs = go_decls(f.read())
        out = [MODULE_HEAD.replace("@CDEFS@", repr("\n".join(typedefs + list(cdefs.values()))))]
        for entry in self.funcs:
            if entry[0] == "complex":
                _, name, nargs = entry
                out.append(complex_wrapper(name, nargs, name in cdefs))
            else:
                _, name, ret, params = entry
                out.append(wrapper(name, ret, params, name in cdefs))
        # Slice_byte's converters exchange a raw pointer+length instead of a
        # PyObject* (see gen_slice.go); they are recognized by name here
        # rather than recorded via add_function, since their python bodies
        # aren't derived from a plain C signature.
        if "Slice_byte_from_bytes" in cdefs and "Slice_byte_to_bytes_ptr" in cdefs:
            out.append(BYTES_FUNCS)
        with open(os.path.join(here, self.name + ".py"), "w") as f:
            f.write("\n".join(out))


def add_checked_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.add_function(name, retval, params)


add_checked_string_function = add_checked_function


def go_decls(header):
    """Returns the Go typedefs (plus any "struct X { ... };" body -- cgo emits
    one ahead of a multi-value-returning export, see genFuncComplexCFFI in
    gen_func.go), and {function name: cdef line} for the functions cgo exports.
    """
    typedefs = []
    decls = {}
    ffi = cffi.FFI()
    lines = header.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"struct (\w+) \{$", line)
        if m:
            block = [line]
            i += 1
            while i < len(lines) and lines[i] != "};":
                block.append(lines[i])
                i += 1
            block.append("};")
            i += 1
            decl = "\n".join(block)
            try:
                ffi.cdef(decl)
                typedefs.append(decl)
            except Exception as err:
                print("gopy: cffi cannot declare struct %s: %s" % (m.group(1), err), file=sys.stderr)
            continue
        if re.match(r"typedef [\w ]+ Go\w+;$", line):
            try:
                ffi.cdef(line)
                typedefs.append(line)
            except Exception:
                pass  # e.g. GoComplex64: not used by exports
            i += 1
            continue
        m = re.match(r"extern (.*?(\w+)\(.*\));$", line.replace("__declspec(dllexport) ", ""))
        if not m or "_GoString_" in line:
            i += 1
            continue
        # cffi takes a plain char as a byte string only; the integer kinds
        # (bool, int8, byte) are passed as ints, with the same C ABI.
        decl = re.sub(r"\b(?<!unsigned )(?<!signed )char\b(?!\s*\*)", "signed char", m.group(1)) + ";"
        try:
            ffi.cdef(decl)
        except Exception as err:
            print("gopy: cffi cannot declare %s: %s" % (m.group(2), err), file=sys.stderr)
            i += 1
            continue
        decls[m.group(2)] = decl
        i += 1
    return typedefs, decls


def wrapper(name, ret, params, exported):
    names = [p[1] for p in params]
    sig = ", ".join(names)
    if not exported or "PyObject*" in [ret] + [p[0] for p in params]:
        return (
            "def %s(*args):\n"
            "    raise NotImplementedError('%s is not available with the cffi backend')\n" % (name, name)
        )
    args = []
    setup = []
    for i, (ctype, pname) in enumerate(params):
        if ctype.startswith("callback:"):
            setup.append(callback_setup(pname, ctype, i + 1))
            args.append("_ffi.cast('void*', _cb_%s)" % pname)
        elif ctype == "char*":
            args.append("_enc(%s, %d)" % (pname, i + 1))
        elif ctype == "bool":
            args.append("(1 if %s else 0)" % pname)
        elif ctype == "uint8_t":
            args.append("_s8(_index(%s))" % pname)
        elif re.match(r"u?int(\d+_t)?$|unsigned int$", ctype):
            args.append("_index(%s)" % pname)
        else:
            args.append(pname)
    body = ["def %s(%s):" % (name, sig)] + setup + ["    _r = _lib.%s(%s)" % (name, ", ".join(args))]
    if ret == "char*":
        body.append("    _r = _dec(_r)")
    elif ret == "bool":
        body.append("    _r = bool(_r)")
    elif ret == "uint8_t":
        body.append("    _r = _r & 0xFF")
    body.append("    _check()")
    if ret is not None:
        body.append("    return _r")
    return "\n".join(body) + "\n"


def callback_setup(pname, ctype, argn):
    """Returns the python source that wraps the callable pname in an
    ffi.callback, for the C signature in ctype
    ("callback:<result or void>(<parameter types>)", see cffi_callback.go).
    The wrapper passes it on to Go as _cb_<pname>, which is kept referenced by
    this local variable until the Go call returns: cffi frees a callback as
    soon as nothing refers to it.

    If the callable raises, cffi prints the traceback and returns 0 to Go.
    """
    ret, _, rest = ctype[len("callback:"):].partition("(")
    ctypes = [t for t in rest[:-1].split(",") if t]
    names = ["a%d" % i for i in range(len(ctypes))]
    conv = []
    for n, t in zip(names, ctypes):
        if t == "char*":
            conv.append('_ffi.string(%s).decode("utf-8")' % n)
        elif t == "bool":
            conv.append("bool(%s)" % n)
        else:
            conv.append(n)
    call = "%s(%s)" % (pname, ", ".join(conv))
    if ret == "void":
        body = call
    elif ret == "bool":
        body = "return 1 if %s else 0" % call
    else:
        body = "return %s" % call

    def cdecl_type(t):
        return "unsigned char" if t == "bool" else t

    cdecl = "%s(%s)" % (cdecl_type(ret), ", ".join(cdecl_type(t) for t in ctypes))
    return "\n".join([
        "    if not callable(%s):" % pname,
        "        raise TypeError('argument %d must be callable, not %%s' %% type(%s).__name__)" % (argn, pname),
        "    def _cbfn_%s(%s):" % (pname, ", ".join(names)),
        "        %s" % body,
        "    _cb_%s = _ffi.callback(%r, _cbfn_%s)" % (pname, cdecl, pname),
    ])


def complex_wrapper(name, nargs, exported):
    """A plain function whose every argument and return value is
    complex64/128 (see genFuncComplexCFFI, gen_func.go): each argument
    crosses as two floats (.real, .imag), and the return value comes back
    as the {r0, r1} struct cgo generates for a two-value Go return.
    """
    if not exported:
        return (
            "def %s(*args):\n"
            "    raise NotImplementedError('%s is not available with the cffi backend')\n" % (name, name)
        )
    names = ["c%d" % i for i in range(nargs)]
    sig = ", ".join(names)
    callargs = ", ".join("%s.real, %s.imag" % (n, n) for n in names)
    return (
        "def %s(%s):\n"
        "    _r = _lib.%s(%s)\n"
        "    _check()\n"
        "    return complex(_r.r0, _r.r1)\n" % (name, sig, name, callargs)
    )


MODULE_HEAD = '''# python bindings for package @NAME@ using cffi.
# File is generated by gopy version @VERSION@. Do not edit.
import builtins
import ctypes
import os
from operator import index as _index

import cffi

_ffi = cffi.FFI()
_ffi.cdef(@CDEFS@)
_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "@NAME@_go@LIBEXT@")
_lib = _ffi.dlopen(_path)
# Go cannot unload its runtime.  cffi unloads _lib at interpreter shutdown but
# ctypes never unloads, so this second handle keeps the library loaded until
# the process exits, as for an extension module.
_pin = ctypes.CDLL(_path)


def _enc(s, argn):
    if not isinstance(s, str):
        raise TypeError("argument %d must be str, not %s" % (argn, type(s).__name__))
    return s.encode("utf-8")


def _dec(p):
    """Copies a malloc'd C string into a str and frees it."""
    if p == _ffi.NULL:
        return None
    try:
        return _ffi.string(p).decode("utf-8")
    finally:
        _lib.GopyFreeString(p)


def _s8(v):
    return ((v + 128) & 0xFF) - 128


def _check():
    """Raises the exception, if any, that the last Go call recorded."""
    e = _lib.GopyTakeError()
    if e != _ffi.NULL:
        kind, _, msg = _dec(e).partition(":")
        raise getattr(builtins, kind, RuntimeError)(msg)

'''

BYTES_FUNCS = '''
def Slice_byte_from_bytes(b):
    if not isinstance(b, (bytes, bytearray)):
        raise TypeError("argument 1 must be bytes, not %s" % type(b).__name__)
    _r = _lib.Slice_byte_from_bytes(_ffi.from_buffer(b), len(b))
    _check()
    return _r


def Slice_byte_to_bytes(handle):
    n = _lib.Slice_byte_to_bytes_len(handle)
    _check()
    if n == 0:
        return b""
    ptr = _lib.Slice_byte_to_bytes_ptr(handle)
    _check()
    try:
        return bytes(_ffi.buffer(ptr, n))
    finally:
        _lib.Slice_byte_free_ptr(ptr)
'''

mod = Module('_@NAME@')
mod.add_include('"@NAME@_go.h"')
mod.add_function('GoPyInit', None, [])
mod.add_function('DecRef', None, [param('int64_t', 'handle')])
mod.add_function('IncRef', None, [param('int64_t', 'handle')])
mod.add_function('NumHandles', retval('int'), [])
mod.add_function('RequestGC', None, [])
mod.add_function('_gopy_clear_go_tls', None, [])
