// Copyright 2026 The go-python Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bind

import (
	_ "embed"
	"fmt"
	"strings"
)

// The cffi backend (GOPY_BACKEND=cffi) generates the same cgo shim as the
// default backend, minus every call into the CPython C API: the shim is a
// plain C shared library that Python loads with cffi.  Errors are recorded
// for the Python side to raise, instead of being set with PyErr_SetString.

//go:embed cffi_build.py
var cffiBuildPy string

func (g *pyGen) isCFFI() bool {
	return g.cfg.Backend == BackendCFFI
}

func (g *pyGen) isPyBind11() bool {
	return g.cfg.Backend == BackendPyBind11
}

// noAPIShim reports whether the exported Go functions must avoid the
// CPython C API: true for every backend whose python-facing wrapper is
// produced from outside the Go build (cffi loads a plain shared library;
// pybind11 compiles a C++ file against the same one).  Both share the shim
// this decides the shape of -- see cffi_callback.go and the complex64/128
// and byte-slice handling below and in gen_slice.go -- and each then has its
// own way of consuming it (cffiBuildPreamble here, pybind11BuildPreamble in
// pybind11.go).
func (g *pyGen) noAPIShim() bool {
	return g.isCFFI() || g.isPyBind11()
}

// cffiBuildPreamble returns the start of build.py: the cffi recorder.
func (g *pyGen) cffiBuildPreamble() string {
	return strings.NewReplacer(
		"@NAME@", g.cfg.Name,
		"@CMD@", g.cfg.Cmd,
		"@VERSION@", g.cfg.Version,
		"@LIBEXT@", g.libext,
	).Replace(cffiBuildPy)
}

// goSetError returns Go code that records an error for Python to raise.
// kind is the name of a Python builtin exception, msg a Go string expression.
func (g *pyGen) goSetError(kind, msg string) string {
	return "gopySetError(\"" + kind + "\", " + msg + ")\n"
}

func isComplexSym(sym *symbol) bool {
	return sym != nil && (sym.goname == "complex64" || sym.goname == "complex128")
}

// A complex64/complex128 value has no single C type that cffi can declare
// (cgo's is _Complex), and cgo won't export a struct, so under cffi it crosses
// as two floats: as two parameters (<name>_re, <name>_im), and as a result in
// cgo's two-value return, which it exports as a plain C struct {r0; r1;}.
// The methods below say how a value of a given symbol crosses, so that the
// generators only differ from the default backend here.

// isCFFIComplex reports whether sym crosses as two floats.
func (g *pyGen) isCFFIComplex(sym *symbol) bool {
	return g.isCFFI() && isComplexSym(sym)
}

// cffiComplexFloat returns the cgo and the Go float type of the parts of a
// complex64 or complex128 symbol.
func cffiComplexFloat(sym *symbol) (cfloat, gofloat string) {
	if sym.goname == "complex64" {
		return "C.float", "float32"
	}
	return "C.double", "float64"
}

// cgoParam returns the declaration of the parameter of an exported function
// that carries a value of sym.
func (g *pyGen) cgoParam(name string, sym *symbol) string {
	if g.isCFFIComplex(sym) {
		cf, _ := cffiComplexFloat(sym)
		return fmt.Sprintf("%[1]s_re %[2]s, %[1]s_im %[2]s", name, cf)
	}
	return name + " " + sym.cgoname
}

// cgoResult returns the result type of an exported function that returns a
// value of sym.
func (g *pyGen) cgoResult(sym *symbol) string {
	if g.isCFFIComplex(sym) {
		cf, _ := cffiComplexFloat(sym)
		return "(" + cf + ", " + cf + ")"
	}
	return sym.cgoname
}

// cpyName returns the type that build.py records for a value of sym.
// wrapper in cffi_build.py expands complex64 and complex128.
func (g *pyGen) cpyName(sym *symbol) string {
	if g.isCFFIComplex(sym) {
		return sym.goname
	}
	return sym.cpyname
}

// goToCgo returns the Go expression that converts expr, a value of sym, to
// what an exported function returns.
func (g *pyGen) goToCgo(sym *symbol, expr string) string {
	switch {
	case g.isCFFIComplex(sym):
		return sym.goname + "GoToPyCFFI(" + expr + ")"
	case sym.go2py != "":
		return sym.go2py + "(" + expr + ")" + sym.go2pyParenEx
	}
	return expr
}

// cgoToGo returns the Go expression that converts the parameter name, as
// declared by cgoParam, to a value of sym.
func (g *pyGen) cgoToGo(sym *symbol, name string) string {
	switch {
	case g.isCFFIComplex(sym):
		return sym.goname + "PyToGoCFFI(" + name + "_re, " + name + "_im)"
	case sym.py2go != "":
		return sym.py2go + "(" + name + ")" + sym.py2goParenEx
	}
	return name
}

// same argument positions as goPreamble: 1 = name of package, 2 = cmdstr,
// 4 = GoHandle, 5 = CGoHandle, 6 = all imports, 7 = mainstr, 8 = C trampolines for
// callbacks (see cffi_callback.go), 10 = gopy version.
const goPreambleCFFI = `/*
cgo stubs for package %[1]s, for use with cffi or pybind11.
File is generated by gopy version %[10]s. Do not edit.
%[2]s
*/

package main

/*
#include <stdint.h>
#include <stdlib.h>
// pybind11's consumer #includes this same preamble (via the generated
// header) as C++, where bool/thread_local are keywords, not the C ones below.
#if !defined(__cplusplus) && (!defined(__STDC_VERSION__) || (__STDC_VERSION__ < 202311L))
typedef uint8_t bool;
#endif
#if defined(__cplusplus)
#define GOPY_THREAD_LOCAL thread_local
#else
#define GOPY_THREAD_LOCAL _Thread_local
#endif
// Thread-local storage for the last error, read by the python side right
// after the call that set it, on the same OS thread.  Windows gets its own
// branch: mingw's compiler-provided thread-local storage (_Thread_local)
// needs TLS support that a DLL loaded after process start (as cffi and
// ctypes do) isn't guaranteed to have, so this uses the OS API instead,
// which carries no such restriction (see TlsAlloc/TlsGetValue/TlsSetValue).
#ifdef _WIN32
#include <windows.h>
static DWORD gopy_err_tls = TLS_OUT_OF_INDEXES;
static inline void gopy_err_tls_init(void) { gopy_err_tls = TlsAlloc(); }
static inline char* gopy_err_get(void) { return (char*)TlsGetValue(gopy_err_tls); }
static inline void gopy_err_put(char* msg) { TlsSetValue(gopy_err_tls, msg); }
#else
static inline void gopy_err_tls_init(void) {}
static GOPY_THREAD_LOCAL char* gopy_err_msg;
static inline char* gopy_err_get(void) { return gopy_err_msg; }
static inline void gopy_err_put(char* msg) { gopy_err_msg = msg; }
#endif
static inline void gopy_set_err(char* msg) {
	free(gopy_err_get());
	gopy_err_put(msg);
}
static inline char* gopy_take_err(void) {
	char* msg = gopy_err_get();
	gopy_err_put(NULL);
	return msg;
}
%[8]s
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
	"github.com/go-python/gopy/gopyh" // handler
	%[6]s
)

func main() {
	%[7]s
}

//export GoPyInit
func GoPyInit() {
	%[7]s
}

// type for the handle -- int64 for speed (can switch to string)
type GoHandle %[4]s
type CGoHandle %[5]s

// DecRef decrements the reference count for the specified handle
// and deletes it it goes to zero.
//export DecRef
func DecRef(handle CGoHandle) {
	gopyh.DecRef(gopyh.CGoHandle(handle))
}

// IncRef increments the reference count for the specified handle.
//export IncRef
func IncRef(handle CGoHandle) {
	gopyh.IncRef(gopyh.CGoHandle(handle))
}

// NumHandles returns the number of handles currently in use.
//export NumHandles
func NumHandles() int {
	return gopyh.NumHandles()
}

// RequestGC runs Go's garbage collector on a dedicated goroutine, and waits.
//export RequestGC
func RequestGC() {
	done := make(chan struct{})
	_gcReq <- done
	<-done
}

var _gcReq = make(chan chan struct{})

func init() {
	C.gopy_err_tls_init()
	go func() {
		for done := range _gcReq {
			runtime.GC()
			close(done)
		}
	}()
}

// The error of the last call on the calling OS thread, for the python side
// to raise; gopy_err_msg is thread-local so concurrent calls on other
// threads don't see it.
func gopySetError(kind, msg string) {
	C.gopy_set_err(C.CString(kind + ":" + msg))
}

// GopyTakeError returns "Kind:message" for the error recorded by the last
// call on the calling thread and clears it, or NULL if there is none.
// Free with GopyFreeString.
//export GopyTakeError
func GopyTakeError() *C.char {
	return C.gopy_take_err()
}

// GopyFreeString frees a string returned by this library.
//export GopyFreeString
func GopyFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

// gopyCallbackScope guards a python callback passed to Go, which only exists
// while the python call it was passed to is running (see cffi_callback.go):
// close waits for callbacks that are running, and then refuses new ones.
type gopyCallbackScope struct {
	mu   sync.RWMutex
	done bool
}

func (s *gopyCallbackScope) enter() bool {
	s.mu.RLock()
	if s.done {
		s.mu.RUnlock()
		println("gopy: callback called after the python call it was passed to returned")
		return false
	}
	return true
}

func (s *gopyCallbackScope) leave() { s.mu.RUnlock() }

func (s *gopyCallbackScope) close() {
	s.mu.Lock()
	s.done = true
	s.mu.Unlock()
}

// boolGoToPy converts a Go bool to python-compatible C.char
func boolGoToPy(b bool) C.char {
	if b {
		return 1
	}
	return 0
}

// boolPyToGo converts a python-compatible C.Char to Go bool
func boolPyToGo(b C.char) bool {
	return b != 0
}

// errorGoToPy converts a Go error to python-compatible C.CString
func errorGoToPy(e error) *C.char {
	if e != nil {
		return C.CString(e.Error())
	}
	return C.CString("")
}

// complex values cross as two floats, see isCFFIComplex in cffi.go
func complex64GoToPyCFFI(c complex64) (C.float, C.float) {
	return C.float(real(c)), C.float(imag(c))
}

func complex64PyToGoCFFI(re, im C.float) complex64 {
	return complex(float32(re), float32(im))
}

func complex128GoToPyCFFI(c complex128) (C.double, C.double) {
	return C.double(real(c)), C.double(imag(c))
}

func complex128PyToGoCFFI(re, im C.double) complex128 {
	return complex(float64(re), float64(im))
}
`
