// Copyright 2026 The go-python Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bind

import (
	_ "embed"
	"strings"
)

// The cffi backend (GOPY_BACKEND=cffi) generates the same cgo shim as the
// default backend, minus every call into the CPython C API: the shim is a
// plain C shared library that Python loads with cffi.  Errors are recorded
// for the Python side to raise, instead of being set with PyErr_SetString.

//go:embed cffi_build.py
var cffiBuildPy string

func (g *pyGen) isCFFI() bool {
	return g.cfg.Backend == BackendCFFI
}

// cffiBuildPreamble returns the start of build.py: the cffi recorder.
func (g *pyGen) cffiBuildPreamble() string {
	return strings.NewReplacer(
		"@NAME@", g.cfg.Name,
		"@CMD@", g.cfg.Cmd,
		"@VERSION@", g.cfg.Version,
		"@LIBEXT@", g.libext,
	).Replace(cffiBuildPy)
}

// goSetError returns Go code that records an error for Python to raise.
// kind is the name of a Python builtin exception, msg a Go string expression.
func (g *pyGen) goSetError(kind, msg string) string {
	return "gopySetError(\"" + kind + "\", " + msg + ")\n"
}

// same argument positions as goPreamble: 1 = name of package, 2 = cmdstr,
// 4 = GoHandle, 5 = CGoHandle, 6 = all imports, 7 = mainstr, 8 = C trampolines for
// callbacks (see cffi_callback.go), 10 = gopy version.
const goPreambleCFFI = `/*
cgo stubs for package %[1]s, for use with cffi.
File is generated by gopy version %[10]s. Do not edit.
%[2]s
*/

package main

/*
#include <stdint.h>
#include <stdlib.h>
#if !defined(__STDC_VERSION__) || (__STDC_VERSION__ < 202311L)
typedef uint8_t bool;
#endif
%[8]s
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
	"github.com/go-python/gopy/gopyh" // handler
	%[6]s
)

func main() {
	%[7]s
}

//export GoPyInit
func GoPyInit() {
	%[7]s
}

// type for the handle -- int64 for speed (can switch to string)
type GoHandle %[4]s
type CGoHandle %[5]s

// DecRef decrements the reference count for the specified handle
// and deletes it it goes to zero.
//export DecRef
func DecRef(handle CGoHandle) {
	gopyh.DecRef(gopyh.CGoHandle(handle))
}

// IncRef increments the reference count for the specified handle.
//export IncRef
func IncRef(handle CGoHandle) {
	gopyh.IncRef(gopyh.CGoHandle(handle))
}

// NumHandles returns the number of handles currently in use.
//export NumHandles
func NumHandles() int {
	return gopyh.NumHandles()
}

// RequestGC runs Go's garbage collector on a dedicated goroutine, and waits.
//export RequestGC
func RequestGC() {
	done := make(chan struct{})
	_gcReq <- done
	<-done
}

var _gcReq = make(chan chan struct{})

func init() {
	go func() {
		for done := range _gcReq {
			runtime.GC()
			close(done)
		}
	}()
}

// The error of the last call, for the python side to raise.  There is one
// slot for the whole process, so calls from several python threads at once
// can be given each other's errors.
var (
	gopyErrMu  sync.Mutex
	gopyErrMsg string
	gopyHasErr bool
)

func gopySetError(kind, msg string) {
	gopyErrMu.Lock()
	gopyErrMsg, gopyHasErr = kind+":"+msg, true
	gopyErrMu.Unlock()
}

// GopyTakeError returns "Kind:message" for the error recorded by the last
// call and clears it, or NULL if there is none.  Free with GopyFreeString.
//export GopyTakeError
func GopyTakeError() *C.char {
	gopyErrMu.Lock()
	defer gopyErrMu.Unlock()
	if !gopyHasErr {
		return nil
	}
	gopyHasErr = false
	return C.CString(gopyErrMsg)
}

// GopyFreeString frees a string returned by this library.
//export GopyFreeString
func GopyFreeString(s *C.char) {
	C.free(unsafe.Pointer(s))
}

// gopyCallbackScope guards a python callback passed to Go, which only exists
// while the python call it was passed to is running (see cffi_callback.go):
// close waits for callbacks that are running, and then refuses new ones.
type gopyCallbackScope struct {
	mu   sync.RWMutex
	done bool
}

func (s *gopyCallbackScope) enter() bool {
	s.mu.RLock()
	if s.done {
		s.mu.RUnlock()
		println("gopy: callback called after the python call it was passed to returned")
		return false
	}
	return true
}

func (s *gopyCallbackScope) leave() { s.mu.RUnlock() }

func (s *gopyCallbackScope) close() {
	s.mu.Lock()
	s.done = true
	s.mu.Unlock()
}

// boolGoToPy converts a Go bool to python-compatible C.char
func boolGoToPy(b bool) C.char {
	if b {
		return 1
	}
	return 0
}

// boolPyToGo converts a python-compatible C.Char to Go bool
func boolPyToGo(b C.char) bool {
	return b != 0
}

// errorGoToPy converts a Go error to python-compatible C.CString
func errorGoToPy(e error) *C.char {
	if e != nil {
		return C.CString(e.Error())
	}
	return C.CString("")
}
`
