# python build stubs for package @NAME@ (cffi backend)
# File is generated by gopy version @VERSION@. Do not edit.
# @CMD@
#
# The generated build code below is written against the pybindgen API.  Here
# the same calls are only recorded, and Module.generate() then writes a cffi
# (ABI mode) module, _@NAME@.py, that loads @NAME@_go@LIBEXT@ directly.  The
# exact C types come from the extern declarations in cgo's @NAME@_go.h.

import os
import re
import sys

import cffi


def retval(ctype, *a, **kw):
    return ctype


def param(ctype, name, *a, **kw):
    return (ctype, name)


class Module(object):
    def __init__(self, name):
        self.name = name
        self.header = None
        self.funcs = []

    def add_include(self, inc):
        self.header = inc.strip('"')

    def add_function(self, name, ret, params, *a, **kw):
        self.funcs.append((name, ret, params))

    def generate(self):
        here = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(here, self.header)) as f:
            typedefs, cdefs = go_decls(f.read())
        out = [MODULE_HEAD.replace("@CDEFS@", repr("\n".join(typedefs + list(cdefs.values()))))]
        for name, ret, params in self.funcs:
            out.append(wrapper(name, ret, params, name in cdefs))
        with open(os.path.join(here, self.name + ".py"), "w") as f:
            f.write("\n".join(out))


def add_checked_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.add_function(name, retval, params)


add_checked_string_function = add_checked_function


def go_decls(header):
    """Returns the Go typedefs, and {function name: cdef line} for the functions cgo exports."""
    typedefs = []
    decls = {}
    ffi = cffi.FFI()
    for line in header.split("\n"):
        if re.match(r"typedef [\w ]+ Go\w+;$", line):
            try:
                ffi.cdef(line)
                typedefs.append(line)
            except Exception:
                pass  # e.g. GoComplex64: not used by exports
            continue
        m = re.match(r"extern (.*?(\w+)\(.*\));$", line.replace("__declspec(dllexport) ", ""))
        if not m or "_GoString_" in line:
            continue
        # cffi takes a plain char as a byte string only; the integer kinds
        # (bool, int8, byte) are passed as ints, with the same C ABI.
        decl = re.sub(r"\b(?<!unsigned )(?<!signed )char\b(?!\s*\*)", "signed char", m.group(1)) + ";"
        try:
            ffi.cdef(decl)
        except Exception as err:
            print("gopy: cffi cannot declare %s: %s" % (m.group(2), err), file=sys.stderr)
            continue
        decls[m.group(2)] = decl
    return typedefs, decls


def wrapper(name, ret, params, exported):
    names = [p[1] for p in params]
    sig = ", ".join(names)
    if not exported or "PyObject*" in [ret] + [p[0] for p in params]:
        return (
            "def %s(*args):\n"
            "    raise NotImplementedError('%s is not available with the cffi backend')\n" % (name, name)
        )
    args = []
    for i, (ctype, pname) in enumerate(params):
        if ctype == "char*":
            args.append("_enc(%s, %d)" % (pname, i + 1))
        elif ctype == "bool":
            args.append("(1 if %s else 0)" % pname)
        elif ctype == "uint8_t":
            args.append("_s8(_index(%s))" % pname)
        elif re.match(r"u?int(\d+_t)?$|unsigned int$", ctype):
            args.append("_index(%s)" % pname)
        else:
            args.append(pname)
    body = ["def %s(%s):" % (name, sig), "    _r = _lib.%s(%s)" % (name, ", ".join(args))]
    if ret == "char*":
        body.append("    _r = _dec(_r)")
    elif ret == "bool":
        body.append("    _r = bool(_r)")
    elif ret == "uint8_t":
        body.append("    _r = _r & 0xFF")
    body.append("    _check()")
    if ret is not None:
        body.append("    return _r")
    return "\n".join(body) + "\n"


MODULE_HEAD = '''# python bindings for package @NAME@ using cffi.
# File is generated by gopy version @VERSION@. Do not edit.
import builtins
import os
from operator import index as _index

import cffi

_ffi = cffi.FFI()
_ffi.cdef(@CDEFS@)
_lib = _ffi.dlopen(os.path.join(os.path.dirname(os.path.abspath(__file__)), "@NAME@_go@LIBEXT@"))


def _enc(s, argn):
    if not isinstance(s, str):
        raise TypeError("argument %d must be str, not %s" % (argn, type(s).__name__))
    return s.encode("utf-8")


def _dec(p):
    """Copies a malloc'd C string into a str and frees it."""
    if p == _ffi.NULL:
        return None
    try:
        return _ffi.string(p).decode("utf-8")
    finally:
        _lib.GopyFreeString(p)


def _s8(v):
    return ((v + 128) & 0xFF) - 128


def _check():
    """Raises the exception, if any, that the last Go call recorded."""
    e = _lib.GopyTakeError()
    if e != _ffi.NULL:
        kind, _, msg = _dec(e).partition(":")
        raise getattr(builtins, kind, RuntimeError)(msg)

'''

mod = Module('_@NAME@')
mod.add_include('"@NAME@_go.h"')
mod.add_function('GoPyInit', None, [])
mod.add_function('DecRef', None, [param('int64_t', 'handle')])
mod.add_function('IncRef', None, [param('int64_t', 'handle')])
mod.add_function('NumHandles', retval('int'), [])
mod.add_function('RequestGC', None, [])
mod.add_function('_gopy_clear_go_tls', None, [])
