# python build stub for package @NAME@ (pybind11 backend)
# File is generated by gopy version @VERSION@. Do not edit.
# @CMD@
#
# The generated build code below is written against the pybindgen API.  Here
# the same calls are only recorded, and Module.generate() then writes
# @NAME@.cpp: a pybind11 module that #includes @NAME@_go.h (cgo's own header)
# and calls the shim functions directly, so -- unlike the cffi backend --
# their C types come from the C++ compiler, not from parsing the header here.


def retval(ctype, *a, **kw):
    return ctype


def param(ctype, name, *a, **kw):
    return (ctype, name)


class Module(object):
    def __init__(self, name, cpp_name):
        self.name = name  # the compiled extension's import name, e.g. "_hi"
        self.cpp_name = cpp_name  # source file to write, e.g. "hi.cpp"
        self.header = None
        self.funcs = []

    def add_include(self, inc):
        self.header = inc.strip('"')

    def add_function(self, name, ret, params, *a, **kw):
        self.funcs.append((name, ret, params))

    def generate(self):
        import os

        here = os.path.dirname(os.path.abspath(__file__))
        defs = [d for d in (wrapper(name, ret, params) for name, ret, params in self.funcs) if d]
        cpp = MODULE_TEMPLATE.replace("@HEADER@", self.header).replace(
            "@DEFS@", "\n".join(defs)
        )
        with open(os.path.join(here, self.cpp_name), "w") as f:
            f.write(cpp)


def add_checked_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.add_function(name, retval, params)


add_checked_string_function = add_checked_function


def wrapper(name, ret, params):
    """Returns the m.def(...) call binding name, or "" if its signature
    isn't supported yet (a PyObject*, i.e. complex64/128 or a callback
    argument): the .cpp simply never binds it, so calling it from python
    raises AttributeError instead of NotImplementedError -- close enough for
    a function nothing in gopy's own generated wrapper calls unconditionally.
    """
    if ret == "PyObject*" or any(p[0] == "PyObject*" for p in params):
        return ""
    args = []
    call_args = []
    for ctype, pname in params:
        if ctype == "char*":
            args.append("const std::string& " + pname)
            call_args.append("const_cast<char*>(%s.c_str())" % pname)
        elif ctype == "bool":
            args.append("bool " + pname)
            call_args.append("(char)(%s ? 1 : 0)" % pname)
        else:
            args.append(ctype + " " + pname)
            call_args.append(pname)
    call = "%s(%s)" % (name, ", ".join(call_args))
    if ret is None:
        body, cpptype = "%s;\n        _check();" % call, "void"
    elif ret == "char*":
        body = (
            "char* _r = %s;\n"
            "        std::string _s(_r ? _r : \"\");\n"
            "        free(_r);\n"
            "        _check();\n"
            "        return _s;" % call
        )
        cpptype = "std::string"
    elif ret == "bool":
        body = "auto _r = %s;\n        _check();\n        return _r != 0;" % call
        cpptype = "bool"
    else:
        body = "auto _r = %s;\n        _check();\n        return _r;" % call
        cpptype = ret
    return '    m.def("%s", [](%s) -> %s {\n        %s\n    });' % (
        name,
        ", ".join(args),
        cpptype,
        body,
    )


MODULE_TEMPLATE = '''// python bindings for package @NAME@ using pybind11.
// File is generated by gopy version @VERSION@. Do not edit.
#include <cstdlib>
#include <string>

#include <pybind11/pybind11.h>

namespace py = pybind11;

extern "C" {
#include "@HEADER@"
}

// Raises the exception, if any, that the last Go call on this thread
// recorded (see gopySetError/GopyTakeError, shared with the cffi backend).
static inline void _check() {
    char* e = GopyTakeError();
    if (!e) {
        return;
    }
    std::string s(e);
    free(e);
    auto sep = s.find(':');
    std::string kind = sep == std::string::npos ? s : s.substr(0, sep);
    std::string msg = sep == std::string::npos ? "" : s.substr(sep + 1);
    PyObject* exc = PyExc_RuntimeError;
    if (kind == "ValueError") exc = PyExc_ValueError;
    else if (kind == "TypeError") exc = PyExc_TypeError;
    else if (kind == "KeyError") exc = PyExc_KeyError;
    else if (kind == "IndexError") exc = PyExc_IndexError;
    else if (kind == "AttributeError") exc = PyExc_AttributeError;
    PyErr_SetString(exc, msg.c_str());
    throw py::error_already_set();
}

PYBIND11_MODULE(_@NAME@, m) {
    // gen_slice.go always exports these 4 (under noAPIShim()) for the
    // built-in byte slice, regardless of whether the package uses []byte;
    // they exchange a raw pointer+length rather than a PyObject*, same as
    // the cffi backend, but bound directly here rather than by name-sniffing
    // the header (cffi_build.py's BYTES_FUNCS) since nothing here needs to.
    m.def("Slice_byte_from_bytes", [](py::bytes b) -> int64_t {
        std::string s = b;
        return Slice_byte_from_bytes(const_cast<char*>(s.data()), (long long)s.size());
    });
    m.def("Slice_byte_to_bytes", [](int64_t handle) -> py::bytes {
        long long n = Slice_byte_to_bytes_len(handle);
        if (n == 0) {
            return py::bytes("", 0);
        }
        void* ptr = Slice_byte_to_bytes_ptr(handle);
        py::bytes result(static_cast<const char*>(ptr), (size_t)n);
        Slice_byte_free_ptr(ptr);
        return result;
    });
@DEFS@
}
'''

mod = Module('_@NAME@', '@NAME@.cpp')
mod.add_include('"@NAME@_go.h"')
mod.add_function('GoPyInit', None, [])
mod.add_function('DecRef', None, [param('int64_t', 'handle')])
mod.add_function('IncRef', None, [param('int64_t', 'handle')])
mod.add_function('NumHandles', retval('int'), [])
mod.add_function('RequestGC', None, [])
