# python build stub for package @NAME@ (pybind11 backend)
# File is generated by gopy version @VERSION@. Do not edit.
# @CMD@
#
# The generated build code below is written against the pybindgen API.  Here
# the same calls are only recorded, and Module.generate() then writes
# @NAME@.cpp: a pybind11 module that #includes @NAME@_go.h (cgo's own header)
# and calls the shim functions directly, so -- unlike the cffi backend --
# their C types come from the C++ compiler, not from parsing the header here.


def retval(ctype, *a, **kw):
    return ctype


def param(ctype, name, *a, **kw):
    return (ctype, name)


class Module(object):
    def __init__(self, name, cpp_name):
        self.name = name  # the compiled extension's import name, e.g. "_hi"
        self.cpp_name = cpp_name  # source file to write, e.g. "hi.cpp"
        self.header = None
        self.funcs = []

    def add_include(self, inc):
        self.header = inc.strip('"')

    def add_function(self, name, ret, params, *a, **kw):
        self.funcs.append((name, ret, params))

    def generate(self):
        import os

        here = os.path.dirname(os.path.abspath(__file__))
        # a callback's C++ trampoline is shared by every callable of the same
        # shape (see pybind11_callback.go), keyed and numbered here in the
        # same first-seen order Go numbered them in, so "gopy_cb_<i>" means
        # the same thing on both sides without the two ever exchanging it.
        callback_kinds = {}
        defs = [d for d in (wrapper(name, ret, params, callback_kinds) for name, ret, params in self.funcs) if d]
        trampolines = "\n".join(callback_trampoline(ctype, i) for ctype, i in callback_kinds.items())
        cpp = (
            MODULE_TEMPLATE.replace("@HEADER@", self.header)
            .replace("@CALLBACK_TRAMPOLINES@", trampolines)
            .replace("@DEFS@", "\n".join(defs))
        )
        with open(os.path.join(here, self.cpp_name), "w") as f:
            f.write(cpp)


def add_checked_function(mod, name, retval, params, failure_expression="", *a, **kw):
    mod.add_function(name, retval, params)


add_checked_string_function = add_checked_function


def wrapper(name, ret, params, callback_kinds):
    """Returns the m.def(...) call binding name, or "" if its signature
    isn't supported yet (a raw PyObject*): the .cpp simply never binds it, so
    calling it from python raises AttributeError instead of
    NotImplementedError -- close enough for a function nothing in gopy's own
    generated wrapper calls unconditionally.  callback_kinds is shared across
    every call from Module.generate, one entry per distinct callback shape
    seen so far (see there and callback_trampoline).
    """
    if ret == "PyObject*" or any(p[0] == "PyObject*" for p in params):
        return ""
    args = []
    setup = []
    call_args = []
    for ctype, pname in params:
        if ctype == "char*":
            args.append("const std::string& " + pname)
            call_args.append("const_cast<char*>(%s.c_str())" % pname)
        elif ctype == "bool":
            args.append("bool " + pname)
            call_args.append("(char)(%s ? 1 : 0)" % pname)
        elif ctype in ("complex64", "complex128"):
            cxxfloat = "float" if ctype == "complex64" else "double"
            args.append("std::complex<%s> %s" % (cxxfloat, pname))
            call_args.append("%s.real(), %s.imag()" % (pname, pname))
        elif ctype.startswith("callback:"):
            i = callback_kinds.setdefault(ctype, len(callback_kinds))
            args.append("py::function " + pname)
            setup.append(
                "int64_t _h_%s = gopy_cb_register(%s);\n"
                "        GopyCBGuard _g_%s{_h_%s};" % (pname, pname, pname, pname)
            )
            call_args.append("_h_%s" % pname)
        else:
            args.append(ctype + " " + pname)
            call_args.append(pname)
    call = "%s(%s)" % (name, ", ".join(call_args))
    # Releasing the GIL only around the call itself (not the setup/result
    # handling around it, which need it) matches what cffi gets for free
    # from ctypes/cffi's own default behavior, and is what makes a callback
    # arrive correctly rather than deadlock: Go may run it from a goroutine
    # (see InGoroutine in _examples/callbacks) while this call's own thread
    # blocks waiting for that goroutine, so it must not be left holding the
    # only GIL there is.
    if ret is None:
        call = "[&]{ py::gil_scoped_release _rel; %s; }()" % call
    else:
        call = "[&]{ py::gil_scoped_release _rel; return %s; }()" % call
    if ret is None:
        body, cpptype = "%s;\n        _check();" % call, "void"
    elif ret == "char*":
        body = (
            "char* _r = %s;\n"
            "        std::string _s(_r ? _r : \"\");\n"
            "        free(_r);\n"
            "        _check();\n"
            "        return _s;" % call
        )
        cpptype = "std::string"
    elif ret == "bool":
        body = "auto _r = %s;\n        _check();\n        return _r != 0;" % call
        cpptype = "bool"
    elif ret in ("complex64", "complex128"):
        cxxfloat = "float" if ret == "complex64" else "double"
        cpptype = "std::complex<%s>" % cxxfloat
        body = (
            "auto _r = %s;\n"
            "        _check();\n"
            "        return %s(_r.r0, _r.r1);" % (call, cpptype)
        )
    else:
        body = "auto _r = %s;\n        _check();\n        return _r;" % call
        cpptype = ret
    if setup:
        body = "\n        ".join(setup) + "\n        " + body
    return '    m.def("%s", [](%s) -> %s {\n        %s\n    });' % (
        name,
        ", ".join(args),
        cpptype,
        body,
    )


def callback_trampoline(ctype, idx):
    """Returns the static gopy_cb_<idx> trampoline for the callback shape in
    ctype ("callback:<result or void>(<parameter types>)", see cffiCallback
    in cffi_callback.go): the Go closure for every callable of this shape
    calls gopy_cb_<idx>, passing its own registry handle as the first
    argument (see pybind11CallbackLit in pybind11_callback.go).
    """
    ret, _, rest = ctype[len("callback:") :].partition("(")
    ctypes_ = [t for t in rest[:-1].split(",") if t]
    names = ["a%d" % i for i in range(len(ctypes_))]

    def cxxparam(t):
        return "unsigned char" if t == "bool" else t

    params = "".join(", %s %s" % (cxxparam(t), n) for t, n in zip(ctypes_, names))
    call_args = []
    for t, n in zip(ctypes_, names):
        if t == "char*":
            call_args.append("%s ? py::str(%s) : py::str()" % (n, n))
        elif t == "bool":
            call_args.append("py::bool_(%s != 0)" % n)
        else:
            call_args.append(n)
    call = "fn(%s)" % ", ".join(call_args)
    cxxret = "void" if ret == "void" else cxxparam(ret)
    zero = "" if ret == "void" else " 0"
    if ret == "void":
        body = "%s;" % call
    elif ret == "bool":
        body = "return %s.cast<bool>() ? 1 : 0;" % call
    else:
        body = "return %s.cast<%s>();" % (call, ret)
    # A raised exception must not reach the extern "C" boundary as a C++
    # exception: unwinding through Go's compiled call frames is undefined
    # behavior (a hard crash in practice).  Printing it and returning the
    # zero value instead matches what cffi's ffi.callback does by default.
    body = (
        "try {\n"
        "        %s\n"
        "    } catch (py::error_already_set& e) {\n"
        "        e.restore();\n"
        "        PyErr_Print();\n"
        "        return%s;\n"
        "    }" % (body, zero)
    )
    return (
        # gil must be declared (and so acquired) before fn: C++ destroys
        # locals in reverse declaration order, and fn (a py::function) needs
        # the GIL held for its own destructor -- declared the other way
        # around, gil would release it first, and fn would decref without it.
        'extern "C" %s gopy_cb_%d(int64_t h%s) {\n'
        "    py::gil_scoped_acquire gil;\n"
        "    py::function fn;\n"
        "    if (!gopy_cb_lookup(h, fn)) {\n"
        "        return%s;\n"
        "    }\n"
        "    %s\n"
        "}" % (cxxret, idx, params, zero, body)
    )


MODULE_TEMPLATE = '''// python bindings for package @NAME@ using pybind11.
// File is generated by gopy version @VERSION@. Do not edit.
#include <complex>
#include <cstdint>
#include <cstdlib>
#include <mutex>
#include <string>
#include <unordered_map>

#include <pybind11/complex.h>
#include <pybind11/functional.h>
#include <pybind11/pybind11.h>

namespace py = pybind11;

extern "C" {
#include "@HEADER@"
}

// Raises the exception, if any, that the last Go call on this thread
// recorded (see gopySetError/GopyTakeError, shared with the cffi backend).
static inline void _check() {
    char* e = GopyTakeError();
    if (!e) {
        return;
    }
    std::string s(e);
    free(e);
    auto sep = s.find(':');
    std::string kind = sep == std::string::npos ? s : s.substr(0, sep);
    std::string msg = sep == std::string::npos ? "" : s.substr(sep + 1);
    PyObject* exc = PyExc_RuntimeError;
    if (kind == "ValueError") exc = PyExc_ValueError;
    else if (kind == "TypeError") exc = PyExc_TypeError;
    else if (kind == "KeyError") exc = PyExc_KeyError;
    else if (kind == "IndexError") exc = PyExc_IndexError;
    else if (kind == "AttributeError") exc = PyExc_AttributeError;
    PyErr_SetString(exc, msg.c_str());
    throw py::error_already_set();
}

// A python callable passed as a func-typed argument is registered here for
// the duration of the call it was passed to (see pybind11_callback.go for
// why a registry rather than one C function pointer per callable), and the
// trampolines below (one per callback shape, see callback_trampoline in
// pybind11_build.py) look it up by handle each time Go calls back in.
static std::mutex gopy_cb_mutex;
static std::unordered_map<int64_t, py::function> gopy_cb_registry;
static int64_t gopy_cb_next = 1;

static int64_t gopy_cb_register(py::function fn) {
    std::lock_guard<std::mutex> lock(gopy_cb_mutex);
    int64_t h = gopy_cb_next++;
    gopy_cb_registry[h] = std::move(fn);
    return h;
}

static void gopy_cb_unregister(int64_t h) {
    std::lock_guard<std::mutex> lock(gopy_cb_mutex);
    gopy_cb_registry.erase(h);
}

// Unregisters a callback's handle once the call it was passed to returns,
// even if that call raised: playing the same role gopyCallbackScope plays
// for cffi.
struct GopyCBGuard {
    int64_t h;
    ~GopyCBGuard() { gopy_cb_unregister(h); }
};

// Looks up the callable registered under h, or returns false if the call it
// was passed to has already returned (h was never valid, or was already
// unregistered).  The caller must already hold the GIL (see
// callback_trampoline in pybind11_build.py for why it acquires that itself,
// rather than here).
static bool gopy_cb_lookup(int64_t h, py::function& out) {
    std::lock_guard<std::mutex> lock(gopy_cb_mutex);
    auto it = gopy_cb_registry.find(h);
    if (it == gopy_cb_registry.end()) {
        return false;
    }
    out = it->second;
    return true;
}

@CALLBACK_TRAMPOLINES@

PYBIND11_MODULE(_@NAME@, m) {
    // gen_slice.go always exports these 4 (under noAPIShim()) for the
    // built-in byte slice, regardless of whether the package uses []byte;
    // they exchange a raw pointer+length rather than a PyObject*, same as
    // the cffi backend, but bound directly here rather than by name-sniffing
    // the header (cffi_build.py's BYTES_FUNCS) since nothing here needs to.
    m.def("Slice_byte_from_bytes", [](py::bytes b) -> int64_t {
        std::string s = b;
        return Slice_byte_from_bytes(const_cast<char*>(s.data()), (long long)s.size());
    });
    m.def("Slice_byte_to_bytes", [](int64_t handle) -> py::bytes {
        long long n = Slice_byte_to_bytes_len(handle);
        if (n == 0) {
            return py::bytes("", 0);
        }
        void* ptr = Slice_byte_to_bytes_ptr(handle);
        py::bytes result(static_cast<const char*>(ptr), (size_t)n);
        Slice_byte_free_ptr(ptr);
        return result;
    });
@DEFS@
}
'''

mod = Module('_@NAME@', '@NAME@.cpp')
mod.add_include('"@NAME@_go.h"')
mod.add_function('GoPyInit', None, [])
mod.add_function('DecRef', None, [param('int64_t', 'handle')])
mod.add_function('IncRef', None, [param('int64_t', 'handle')])
mod.add_function('NumHandles', retval('int'), [])
mod.add_function('RequestGC', None, [])
